name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'OS-Q/A21A'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.7]
        tool:
          - "PIO"
          - "QIO"
        examples:
          - "tests/blink"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python: ${{ matrix.python }}

      - name: Install PIO
        if: matrix.tool == 'PIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install https://github.com/OS-Q/P21.git

      - name: Install QIO
        if: matrix.tool == 'QIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install https://github.com/OS-Q/P21.git

      - name: Build
        run: |
          pio run -d ${{ matrix.examples }}
