name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.json'
      - '**.md'
      - keywords.txt
      - CI/**
      - '!CI/build/arduino-cli.py'
      - '!CI/build/platformio-builder.py'
      - '!CI/build/examples/**'
      - tools/**
      - '!tools/platformio-build.py'
  pull_request:
    paths-ignore:
      - '*.json'
      - '**.md'
      - keywords.txt
      - CI/**
      - '!CI/build/arduino-cli.py'
      - '!CI/build/platformio-builder.py'
      - '!CI/build/examples/**'
      - tools/**
      - '!tools/platformio-build.py'

jobs:
  astyle_check:
    runs-on: ubuntu-latest
    name: AStyle check
    steps:
    # First of all, clone the repo using the checkout action.
    - name: Checkout
      uses: actions/checkout@master

    - name: Astyle check
      id: Astyle
      uses: OS-Q/A21/astyle-check@master
      with:
        astyle-definition: 'CI/astyle/.astylerc'
        ignore-path-list: 'CI/astyle/.astyleignore'

    # Use the output from the `Astyle` step
    - name: Astyle Errors
      if: failure()
      run: |
        cat ${{ steps.Astyle.outputs.astyle-result }}
        exit 1

  core_build:
    runs-on: ubuntu-latest
    name: Core compilation
    steps:
    # First of all, clone the repo using the checkout action.
    - name: Checkout
      uses: actions/checkout@master

    - name: Compilation
      id: Compile
      uses: OS-Q/A21/compile-examples@master
      with:
        additional-url: 'https://raw.githubusercontent.com/OS-Q/A21/master/package_stm_index.json'

    # Use the output from the `Compile` step
    - name: Compilation Errors
      if: failure()
      run: |
        cat ${{ steps.Compile.outputs.compile-result }}
        exit 1

  Action_QIO:
    runs-on: ubuntu-latest
    name: Action Build
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: "recursive"
        fetch-depth: 1

    - name: QIO
      id: Compile
      uses: OS-Q/A21/QIO@master
      with:
        board: "blackpill_f103c8"

  test:
    if: github.repository == 'OS-Q/A21A'
    name: Test Build
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python: [3.7]
        tool:
          - "QIO"
        examples:
          - "tests/blink"

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python: ${{ matrix.python }}

      - name: Install PIO
        if: matrix.tool == 'PIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install https://github.com/OS-Q/P21.git

      - name: Install QIO
        if: matrix.tool == 'QIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install https://github.com/OS-Q/P21.git

      - name: Build
        run: |
          pio run -d ${{ matrix.examples }}
