name: nightly

on:
  schedule:
    - cron: '0 14 * * *'


jobs:
  build:
    if: github.repository == 'OS-Q/A21A'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: [3.7,3.9]
        tool:
          - "PIO"
          - "QIO"
        examples:
          - "tests/blink"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install PIO
        if: matrix.tool == 'PIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install https://github.com/OS-Q/P21.git

      - name: Install QIO
        if: matrix.tool == 'QIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install https://github.com/OS-Q/P21.git

      - name: Build
        run: |
          pio run -d ${{ matrix.examples }}

      - name: upload
        uses: actions/upload-artifact@v2
        if: matrix.tool == 'QIO'
        with:
          name: ubuntu-build-A21A
          path: ${{ matrix.examples }}/build

