name: release

on:
  push:
    tags:
      - 'v*'


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'OS-Q/A21A'
    strategy:
      fail-fast: false
      matrix:
        python: [3.7]
        examples:
          - "tests/blink"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python: ${{ matrix.python }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install https://github.com/OS-Q/P21.git

      - name: Get version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build
        run: |
          qio run -d ${{ matrix.examples }}
          echo "#A21A release : " >> CHANGELOG.txt
          echo ${{ github.ref }} >> CHANGELOG.txt
          echo ${{ github.sha }} >> CHANGELOG.txt
          cp build/*.bin ${{ steps.get_version.outputs.VERSION }}.bin
          zip firmware.zip ${{ steps.get_version.outputs.VERSION }}.bin CHANGELOG.txt
          zip docs.zip CHANGELOG.txt

      - name: Release
        uses: stopstopstop/release-action@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            src/CHANGELOG.txt
            src/README.md
        env:
          GITHUB_TOKEN: ${{ secrets.MATISMART }}

      - name: Send firmware
        uses: stopstopstop/mail-action@master
        with:
          server_address:  ${{secrets.MAIL_SERVER}}
          server_port: ${{secrets.MAIL_PORT}}
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: matismart firmware
          body: file://README.md
          to: ${{secrets.MAIL_TO}}
          from: Qitas
          cc: ${{secrets.MAIL_CC}},${{github.event.pusher.email}}
          bcc: ${{secrets.MAIL_BCC}}
          content_type: text/html
          convert_markdown: true
          attachments: src/docs.zip,src/${{ steps.get_version.outputs.VERSION }}.bin,src/firmware.zip

      - name: upload
        uses: stopstopstop/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSHPORT }}
          script: |
            cd /home/github/matismart/release

